In [3]:
import warnings; warnings.filterwarnings("ignore")
import os; from sys import platform
if platform == "darwin":    os.chdir('/Users/ziyingc/Dropbox/Lab/MotorCortex')
elif platform == "win32":   os.chdir('D:\Dropbox\Lab\MotorCortex')
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
import matplotlib.cm as cm; import matplotlib.mlab as mlab
import numpy as np;
import time2frequency as t2f
import behavior_track as bt
import turning_track  as tt
import behavior_plot as bp
import behavior_analysis as ba
import philters
fs = 30000;  fps = 30; fs_out = 1000;  T = 1/fs_out;


In [11]:
erfdn = np.load('Rats/Rats_Turn_ephy.npy')
print(erfdn)
for rfdn in erfdn:
    epn = np.load(rfdn+'tracking'+'/epn_turn_elec_post.npy');
    subset = np.load(rfdn+'tracking'+'/subset_ephy_li.npy');
    fig = plt.figure(1, figsize=(30, len(epn)*2));  
    gs  = GridSpec(int(len(epn)/2)+1 , 2);
    kk = 0
    total_pk=0
    for k in epn:
        fdn  = rfdn + k + '/'
        ts  = np.load(fdn+'tracking'+'/ts_f.npy');  
        spd = np.load(fdn+'tracking/' + 'spd_f.npy');
        idx_clean_f   = np.load(fdn+'tracking/'+'idx_clean_f.npy');
        idx_clean_fft = np.load(fdn+'tracking/'+'idx_clean_fft.npy')
        idx_clean   = np.logical_and(idx_clean_f, idx_clean_fft)
        
        ax_idx = gs[kk];  ax = fig.add_subplot(ax_idx);
        ax.plot(ts, spd);ax.set_ylim([0,30])
        thr1 = 10;
        index, T = philters.read_burst(spd, thr1/2, thr1, idx_clean, 1)
        total_pk = total_pk+len(index)
#         print(k[10:21], len(index))
        ax.set_title(str(len(index)))
        kk += 1
    print(total_pk)
    plt.savefig('pic2/speed_'+rfdn[9:len(rfdn)-1]+'.png')
    plt.clf()

['Rats/Rat_Outlaw/' 'Rats/Rat_Swashbuckler/']
39
67


<Figure size 2160x4752 with 0 Axes>

In [ ]:
erfdn = np.load('Rats/Rats_ephy.npy')[[0]]
print(erfdn)
for rfdn in erfdn:
    epn = np.load(rfdn+'tracking'+'/epn_ephy.npy');
    print(rfdn, len(epn))
#     ba.movement_segment(rfdn, epn, fps, fs_out)
    j = 0;
    total_acc = 0;
    total_dec = 0;
    dispm_ac_Toi2 = np.empty([0,])
    dispm_de_Toi2 = np.empty([0,])
    for k in epn:
        
        fdn   = rfdn + k + '/'
        ts_f  = np.load(fdn+'tracking/'+'ts_f.npy');     spd_f = np.load(fdn+'tracking/'+'spd_f.npy');

        pos_Y = np.load(fdn+'tracking/'+'pos_Y_f.npy');  pos_X = np.load(fdn+'tracking/'+'pos_X_f.npy')

        XY = np.array((pos_X, pos_Y)).T
        TN_max =fps*5;      TN_min =fps*2
        l_t = len(ts_f); T_t = l_t/fps/60
        
        d_s = np.square(np.diff(XY, axis = 0))
        d_XY = np.square(np.sum(d_s,axis=1)); dis_traveled = np.sum(d_XY)
        
        dis = np.empty((0,))
        idx_T = np.empty((0,2))
        i = 0
        while i < l_t-TN_max:
            p_i = XY[i,:];
            for j in np.arange(i+TN_min,i+TN_max):
                p_j = XY[j,:];
#                 l_xy_ij = np.sum(d_XY[i:j])
#                 d_ij = p_i-p_j;
#                 dis = np.sqrt(sum(d_ij*d_ij))

                dis_ij = np.matmul(p_i-p_j, p_i-p_j);
                
            i += 1
#         print(k[10:21], np.round([dis_traveled],2))
#     print(' ')

['Rats/Rat_Swashbuckler/']
Rats/Rat_Swashbuckler/ 23


In [2]:
# import shutil
# # erfdn = np.load('Rats/Rats.npy')
# for rfdn in erfdn:
#     epn = np.load(rfdn+'tracking'+'/epn_ephy.npy');
#     for k in epn:
#         fdn = rfdn + k + '/'
#         try:
#             os.remove(fdn+'tracking/'+'idx_idol.npy')
#             os.remove(fdn+'tracking/'+'idx_idol_f.npy')
#         except OSError as e:
#             print ("Error: %s - %s." % (e.filename, e.strerror))

In [3]:
erfdn = np.load('Rats/Rats_ephy.npy')#[[4]]
mode = 'FFT'
for rfdn in erfdn:
    epn    = np.load(rfdn+'tracking'+'/epn_ephy.npy');
    epn_id    = np.load(rfdn+'tracking'+'/epn_ephy_id.npy').astype('int');
    print(epn_id)
    subset = np.load(rfdn+'tracking'+'/subset_ephy_li.npy');
    print(rfdn, len(epn))
    test = True
    bp.plot_tracks(rfdn, epn, epn_id, fs_out)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
Rats/Rat_Swashbuckler/ 21
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
Rats/Rat_Outlaw/ 61
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 0 0 0 0 0 1 1 1]
Rats/Rat_Drifter/ 52
[0 0 0 0 0 0 0 0 0 2 2 2 1 1 1]
Rats/Rat_Unknown/ 15
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 1 1 1]
Rats/Rat_Quartus/ 29
[0 0 0 0 0 0 0 0 0 0 0]
Rats/Rat_Lenny/ 11
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Rats/Rat_Astro/ 17


<Figure size 1440x1440 with 0 Axes>

In [8]:
erfdn = np.load('Rats/Rats_ephy.npy')
l = np.empty((0,))
w = np.empty((0,))

for rfdn in erfdn:
    epn    = np.load(rfdn+'tracking'+'/epn_ephy.npy');
    epn_id = np.load(rfdn+'tracking'+'/epn_ephy_id.npy');
    lth, wd = bt.measurement(rfdn, epn, epn_id, 3);
    idx_TN = epn_id>0
    l_m =np.mean(lth[np.logical_and(idx_TN,lth>420)])
    if l_m > 0:
        l = np.append(l, l_m)
    w_m =np.mean(wd[np.logical_and(idx_TN,wd>190)])
    if w_m > 0:
        w = np.append(w, w_m)
    
                  
l = np.mean(l)
w = np.mean(w)
r_p2cm_w = 20/w*2.54
r_p2cm_l = 43/l*2.54
r_p2cm_lw = np.array([r_p2cm_l, r_p2cm_w])
# np.save('Rats/r_p2cm_TN.npy', r_p2cm_lw)
print('w cm/pixel:', round(r_p2cm_w,3),'l cm/pixel:', round(r_p2cm_l,3))
print('w pixel/cm:', round(1/r_p2cm_w,3),'l pixel/cm:', round(1/r_p2cm_l,3))
#     print(np.round(lth[lth>400],2))
#     print(np.round(wd[wd>180],2))

# linear 46 inches

w cm/pixel: 0.262 l cm/pixel: 0.255
w pixel/cm: 3.819 l pixel/cm: 3.921


In [2]:
erfdn = np.load('Rats/Rats_ephy.npy')
# erfdn = np.load('Rats/Rats_LT_ephy.npy')
# erfdn = np.load('Rats/Rats_Turn.npy')
# erfdn = np.load('Rats/Rats_Turn_ephy.npy')
for rfdn in erfdn:
    epn    = np.load(rfdn+'tracking'+'/epn_ephy.npy');
#     epn    = np.load(rfdn+'tracking'+'/epn_LT_post.npy');
#     epn    = np.load(rfdn+'tracking'+'/epn_LT.npy');
#     epn    = np.load(rfdn+'tracking'+'/epn_turn_elec_post.npy');
    subset = np.load(rfdn+'tracking'+'/subset_ephy_li.npy');
    print(rfdn, len(epn))
    

Rats/Rat_Swashbuckler/ 23
Rats/Rat_Outlaw/ 62
Rats/Rat_Quartus/ 29
Rats/Rat_Unknown/ 16
Rats/Rat_Drifter/ 66
Rats/Rat_Astro/ 17
Rats/Rat_Lenny/ 11


In [3]:
erfdn = np.load('Rats/Rats_Turn_ephy.npy')#[[2]]
Tn_pre = 3;  T_seg = np.arange(5, 150)*1;    
dmax = 15;    dmin  = 8;
dmax2 = 8; dmin2 = 5; T_min = 15;
test = False
for rfdn in erfdn:
    epn = np.load(rfdn+'tracking'+'/epn_turn_elec_post.npy');
    print(rfdn, 'sessions', len(epn))
#     tt.XY_displacement(rfdn, epn, dmax,  dmin,  T_seg, int(Tn_pre*fps), test = test)
#     tt.XY_disp_filter (rfdn, epn, dmax2, dmin2, T_min, test = test)
#     tt.XY_turn_filter (rfdn, epn,     int(Tn_pre*fps), test = test)

Rats/Rat_Outlaw/ sessions 33
Rats/Rat_Swashbuckler/ sessions 11
Rats/Rat_Drifter/ sessions 32
Rats/Rat_Unknown/ sessions 5


In [4]:
erfdn = np.load('Rats/Rats_Turn_ephy.npy')
for rfdn in erfdn:
    epn = np.load(rfdn+'tracking'+'/epn_turn_elec_post.npy');
    print(rfdn, 'sessions', len(epn))
    bp.plot_turnspeed(rfdn, epn, int(Tn_pre*fps), test)

Rats/Rat_Outlaw/ sessions 33
Rats/Rat_Swashbuckler/ sessions 11
Rats/Rat_Drifter/ sessions 32
Rats/Rat_Unknown/ sessions 5


<Figure size 1152x576 with 0 Axes>

# NEW 


In [2]:
erfdn = np.load('Rats/Rats_Turn.npy')

erfdn = [
    'Rats/Rat_Outlaw/',
    'Rats/Rat_Backup_plan/',
    'Rats/Rat_Dragonfly/',

    'Rats/Rat_Drifter/',
    'Rats/Rat_Unknown/',
    'Rats/Rat_Swashbuckler/',
    'Rats/Rat_Quartus/',
    'Rats/Rat_Left/',
]

dmax2 = 20; dmin2 = 15; T_min = 5;
Tn_pre = 1.5;
test = True
for rfdn in erfdn:
    epn = np.load(rfdn+'tracking'+'/epn_turn.npy');
    print(rfdn, 'sessions', len(epn))
#     tt.XY_disp_filter (rfdn, epn, dmax2, dmin2, T_min, test = test)
    tt.XY_turn_filter (rfdn, epn,     int(Tn_pre*fps), test = test)
#     bp.plot_turns(rfdn, epn, int(Tn_pre*fps), test)

Rats/Rat_Outlaw/ sessions 69
total right: 134 total left: 95
Rats/Rat_Backup_plan/ sessions 5
total right: 78 total left: 70
Rats/Rat_Dragonfly/ sessions 5
total right: 77 total left: 78
Rats/Rat_Drifter/ sessions 61
total right: 148 total left: 145
Rats/Rat_Unknown/ sessions 7
total right: 19 total left: 16
Rats/Rat_Swashbuckler/ sessions 23
total right: 59 total left: 54
Rats/Rat_Quartus/ sessions 5
total right: 68 total left: 88
Rats/Rat_Left/ sessions 20
total right: 133 total left: 114
